package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;
import static frc.robot.util.constants.SwerveConstants.AUTO_DRIVE_STATOR_CURRENT_ENABLE;
import static frc.robot.util.constants.SwerveConstants.DRIVE_SUPPLY_CURRENT_ENABLE;
import static frc.robot.util.constants.SwerveConstants.DRIVE_SUPPLY_CURRENT_LIMIT;
import static frc.robot.util.constants.SwerveConstants.DRIVE_SUPPLY_CURRENT_LOWER_LIMIT;
import static frc.robot.util.constants.SwerveConstants.DRIVE_SUPPLY_CURRENT_LOWER_TIME;
import static frc.robot.util.constants.SwerveConstants.TELEOP_DRIVE_STATOR_CURRENT_ENABLE;
import static frc.robot.util.constants.SwerveConstants.TELEOP_DRIVE_STATOR_CURRENT_LIMIT;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import dev.doglog.DogLog;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import java.util.ArrayDeque;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.json.simple.JSONObject;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  // Phoenix 26.3.0 SwerveDrivePoseEstimator retains 1.5 seconds of odometry. Its sampler
  // clamps outside that interval, so retain actual sample timestamps to reject missing history.
  private static final double kPoseHistorySeconds = 1.5;
  private final Object m_poseHistoryLock = new Object();
  private final ArrayDeque<Double> m_poseHistoryTimestamps = new ArrayDeque<>();
  private int m_poseResetsInProgress;
  private double m_poseHistoryNotBefore = Double.NEGATIVE_INFINITY;
  private long m_poseResetSequence;
  private boolean m_fieldHeadingAligned;

  private enum HeadingAlignmentEffect {
    PRESERVE,
    ESTABLISH,
    INVALIDATE
  }

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  /** Swerve request to apply during robot-centric path following */
  private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds =
      new SwerveRequest.ApplyRobotSpeeds();

  /* Swerve requests to apply during SysId characterization */
  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
      new SwerveRequest.SysIdSwerveSteerGains();
  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
      new SwerveRequest.SysIdSwerveRotation();

  /*
   * SysId routine for characterizing translation. This is used to find PID gains
   * for the drive motors.
   */
  private final SysIdRoutine m_sysIdRoutineTranslation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  /*
   * SysId routine for characterizing steer. This is used to find PID gains for
   * the steer motors.
   */
  private final SysIdRoutine m_sysIdRoutineSteer =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(7), // Use dynamic voltage of 7 V
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
          new SysIdRoutine.Mechanism(
              volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

  /*
   * SysId routine for characterizing rotation.
   * This is used to find PID gains for the FieldCentricFacingAngle
   * HeadingController.
   * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
   * importing the log to SysId.
   */
  private final SysIdRoutine m_sysIdRoutineRotation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              /* This is in radians per second², but SysId only supports "volts per second" */
              Volts.of(Math.PI / 6).per(Second),
              /* This is in radians per second, but SysId only supports "volts" */
              Volts.of(Math.PI),
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
              },
              null,
              this));

  /* The SysId routine to test */
  private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    registerTelemetry(null);
    configureAutoDriveCurrentLimits();
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    registerTelemetry(null);
    configureAutoDriveCurrentLimits();
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    registerTelemetry(null);
    configureAutoDriveCurrentLimits();
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
  }

  private void configureAutoBuilder() {
    try {
      var config = RobotConfig.fromGUISettings();
      AutoBuilder.configure(
          () -> getState().Pose, // Supplier of current robot pose
          pose -> resetPose(pose, "PATHPLANNER_AUTO"), // Consumer for seeding pose against auto
          () -> getState().Speeds, // Supplier of current robot speeds
          // Consumer of ChassisSpeeds and feedforwards to drive the robot
          (speeds, feedforwards) ->
              setControl(
                  m_pathApplyRobotSpeeds
                      .withSpeeds(ChassisSpeeds.discretize(speeds, 0.02))
                      .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                      .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
          new PPHolonomicDriveController(
              // PID constants for translation
              new PIDConstants(5.0, 0.0, 0.0),
              // PID constants for rotation
              new PIDConstants(4.5, 0.0, 0.0)),
          config,
          // Assume the path needs to be flipped for Red vs Blue, this is normally the
          // case
          () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
          this // Subsystem for requirements
          );
    } catch (Exception ex) {
      DriverStation.reportError(
          "Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
    }
  }

  /** Re-applies the unlimited auto drive stator configuration after Phoenix Swerve construction. */
  public void configureAutoDriveCurrentLimits() {
    applyDriveCurrentLimits(createAutoDriveCurrentLimits());
  }

  /** Applies the declared 80 A drive stator limit for teleoperated operation. */
  public void configureTeleopDriveCurrentLimit() {
    applyDriveCurrentLimits(createTeleopDriveCurrentLimits());
  }

  static CurrentLimitsConfigs createAutoDriveCurrentLimits() {
    return addDriveSupplyCurrentLimits(
        new CurrentLimitsConfigs().withStatorCurrentLimitEnable(AUTO_DRIVE_STATOR_CURRENT_ENABLE));
  }

  static CurrentLimitsConfigs createTeleopDriveCurrentLimits() {
    return addDriveSupplyCurrentLimits(
        new CurrentLimitsConfigs()
            .withStatorCurrentLimitEnable(TELEOP_DRIVE_STATOR_CURRENT_ENABLE)
            .withStatorCurrentLimit(TELEOP_DRIVE_STATOR_CURRENT_LIMIT));
  }

  private static CurrentLimitsConfigs addDriveSupplyCurrentLimits(
      CurrentLimitsConfigs currentLimits) {
    return currentLimits
        .withSupplyCurrentLimitEnable(DRIVE_SUPPLY_CURRENT_ENABLE)
        .withSupplyCurrentLimit(DRIVE_SUPPLY_CURRENT_LIMIT)
        .withSupplyCurrentLowerLimit(DRIVE_SUPPLY_CURRENT_LOWER_LIMIT)
        .withSupplyCurrentLowerTime(DRIVE_SUPPLY_CURRENT_LOWER_TIME);
  }

  private void applyDriveCurrentLimits(CurrentLimitsConfigs currentLimits) {
    for (var module : getModules()) {
      module.getDriveMotor().getConfigurator().apply(currentLimits);
    }
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Runs the SysId Quasistatic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Quasistatic test
   * @return Command to run
   */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

  @Override
  public void periodic() {
    DogLog.time("Perf/Swerve");
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply
     * it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts
     * mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is
     * disabled.
     * This ensures driving behavior doesn't change until an explicit disable event
     * occurs during testing.
     */
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }
    DogLog.timeEnd("Perf/Swerve");
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, timestampSeconds);
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta]ᵀ, with units in meters and radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(visionRobotPoseMeters, timestampSeconds, visionMeasurementStdDevs);
  }

  /**
   * Samples the CTRE estimator only when its odometry history covers the requested FPGA time.
   *
   * @param timestampSeconds Capture timestamp in FPGA seconds, not CTRE current-time seconds.
   * @return The latency-compensated pose, or empty for missing, expired, future, or pre-reset
   *     history.
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    if (!Double.isFinite(timestampSeconds)) return Optional.empty();
    double ctreTimestamp = Utils.fpgaToCurrentTime(timestampSeconds);
    long resetSequence;
    synchronized (m_poseHistoryLock) {
      if (!hasPoseHistory(ctreTimestamp)) return Optional.empty();
      resetSequence = m_poseResetSequence;
    }
    // Never hold the history lock across JNI: the odometry callback also acquires it.
    Optional<Pose2d> pose = super.samplePoseAt(ctreTimestamp);
    synchronized (m_poseHistoryLock) {
      return resetSequence == m_poseResetSequence && hasPoseHistory(ctreTimestamp)
          ? pose
          : Optional.empty();
    }
  }

  /** Keeps internal history tracking active when an external telemetry consumer changes. */
  @Override
  public void registerTelemetry(Consumer<SwerveDriveState> telemetryFunction) {
    super.registerTelemetry(
        state -> {
          synchronized (m_poseHistoryLock) {
            double timestamp = state.Timestamp;
            if (m_poseResetsInProgress == 0
                && Double.isFinite(timestamp)
                && timestamp > m_poseHistoryNotBefore
                && (m_poseHistoryTimestamps.isEmpty()
                    || timestamp > m_poseHistoryTimestamps.getLast())) {
              m_poseHistoryTimestamps.addLast(timestamp);
              while (timestamp - m_poseHistoryTimestamps.getFirst() > kPoseHistorySeconds) {
                m_poseHistoryTimestamps.removeFirst();
              }
            }
          }
          if (telemetryFunction != null) telemetryFunction.accept(state);
        });
  }

  // Caller holds m_poseHistoryLock; this method never calls JNI.
  private boolean hasPoseHistory(double timestamp) {
    return m_poseResetsInProgress == 0
        && !m_poseHistoryTimestamps.isEmpty()
        && timestamp >= m_poseHistoryTimestamps.getFirst()
        && timestamp <= m_poseHistoryTimestamps.getLast();
  }

  /**
   * Whether an explicit absolute-field pose/rotation reset has anchored the gyro heading.
   * Operator-relative zeroing and taring do not establish an absolute field heading.
   */
  public boolean isFieldHeadingAligned() {
    synchronized (m_poseHistoryLock) {
      return m_poseResetsInProgress == 0 && m_fieldHeadingAligned;
    }
  }

  @Override
  public void resetPose(Pose2d pose) {
    resetPose(pose, "EXTERNAL_RESET");
  }

  /** Resets the native estimator and records why its coordinate origin changed. */
  public void resetPose(Pose2d pose, String reason) {
    runPoseReset(() -> super.resetPose(pose), reason, pose, HeadingAlignmentEffect.ESTABLISH);
  }

  @Override
  public void resetTranslation(Translation2d translation) {
    runPoseReset(
        () -> super.resetTranslation(translation),
        "RESET_TRANSLATION",
        new Pose2d(translation, getState().Pose.getRotation()),
        HeadingAlignmentEffect.PRESERVE);
  }

  @Override
  public void resetRotation(Rotation2d rotation) {
    runPoseReset(
        () -> super.resetRotation(rotation),
        "RESET_ROTATION",
        new Pose2d(getState().Pose.getTranslation(), rotation),
        HeadingAlignmentEffect.ESTABLISH);
  }

  @Override
  public void seedFieldCentric(Rotation2d rotation) {
    runPoseReset(
        () -> super.seedFieldCentric(rotation),
        "OPERATOR_FIELD_CENTRIC_SEED",
        new Pose2d(getState().Pose.getTranslation(), rotation.plus(getOperatorForwardDirection())),
        HeadingAlignmentEffect.INVALIDATE);
  }

  @Override
  public void tareEverything() {
    runPoseReset(
        super::tareEverything, "TARE_EVERYTHING", Pose2d.kZero, HeadingAlignmentEffect.INVALIDATE);
  }

  private void runPoseReset(
      Runnable resetAction, String reason, Pose2d requestedPose, HeadingAlignmentEffect alignment) {
    Pose2d poseBefore = getState().Pose;
    double timestamp = Timer.getFPGATimestamp();
    long sequence;
    synchronized (m_poseHistoryLock) {
      m_poseResetsInProgress++;
      m_poseHistoryTimestamps.clear();
      sequence = ++m_poseResetSequence;
    }
    boolean completed = false;
    try {
      resetAction.run();
      completed = true;
    } finally {
      double resetFinished = Utils.getCurrentTimeSeconds();
      synchronized (m_poseHistoryLock) {
        m_poseHistoryTimestamps.clear();
        m_poseHistoryNotBefore = Math.max(m_poseHistoryNotBefore, resetFinished);
        m_poseResetsInProgress--;
        if (!completed || alignment == HeadingAlignmentEffect.INVALIDATE) {
          m_fieldHeadingAligned = false;
        } else if (alignment == HeadingAlignmentEffect.ESTABLISH) {
          m_fieldHeadingAligned = true;
        }
      }
    }
    Pose2d poseAfter = getState().Pose;
    DogLog.log("Swerve/PoseReset/Sequence", sequence);
    DogLog.log("Swerve/PoseReset/TimestampSeconds", timestamp);
    DogLog.log("Swerve/PoseReset/Reason", reason);
    DogLog.log("Swerve/PoseReset/PoseBefore", poseBefore);
    DogLog.log("Swerve/PoseReset/RequestedPose", requestedPose);
    DogLog.log("Swerve/PoseReset/PoseAfter", poseAfter);
    DogLog.log("Swerve/PoseReset/Enabled", DriverStation.isEnabled());
    DogLog.log("Swerve/PoseReset/Autonomous", DriverStation.isAutonomous());
    Map<String, Object> event = new LinkedHashMap<>();
    event.put("schemaVersion", 1);
    event.put("event", "POSE_RESET");
    event.put("sequence", sequence);
    event.put("timestampSeconds", timestamp);
    event.put("reason", reason);
    event.put("poseBefore", poseCoordinates(poseBefore));
    event.put("requested", poseCoordinates(requestedPose));
    event.put("poseAfter", poseCoordinates(poseAfter));
    event.put("enabled", DriverStation.isEnabled());
    event.put("autonomous", DriverStation.isAutonomous());
    event.put("fieldHeadingAligned", isFieldHeadingAligned());
    DogLog.log("Swerve/PoseReset/Event", JSONObject.toJSONString(event));
  }

  private static List<Double> poseCoordinates(Pose2d pose) {
    return List.of(pose.getX(), pose.getY(), pose.getRotation().getRadians());
  }

  /** Returns absolute chassis pitch angle in degrees from the Pigeon2 IMU. */
  public double getPitchDegrees() {
    return getPigeon2().getPitch().getValueAsDouble();
  }

  /** Returns absolute chassis roll angle in degrees from the Pigeon2 IMU. */
  public double getRollDegrees() {
    return getPigeon2().getRoll().getValueAsDouble();
  }

  /** True when pitch and roll are both within the provided absolute tilt limit. */
  public boolean isPitchRollStableForVision(double maxAbsTiltDegrees) {
    return Math.abs(getPitchDegrees()) <= maxAbsTiltDegrees
        && Math.abs(getRollDegrees()) <= maxAbsTiltDegrees;
  }
}
